import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:latlong2/latlong.dart';
import 'package:flutter_map_animations/flutter_map_animations.dart';
import 'package:popytka_ua/l10n/app_localizations.dart';
import 'package:popytka_ua/presentation/theme/app_colors.dart';
import 'package:popytka_ua/presentation/widgets/glass_container.dart';
import 'package:popytka_ua/presentation/widgets/address_autocomplete_field.dart';
import 'package:popytka_ua/data/services/search_history_service.dart';
import 'package:popytka_ua/data/services/nominatim_service.dart';

import 'package:go_router/go_router.dart';
import 'package:popytka_ua/data/repositories/ride_repository.dart';
import 'package:popytka_ua/domain/models/ride_model.dart';
import 'package:popytka_ua/data/repositories/ride_request_repository.dart';
import 'package:popytka_ua/domain/models/ride_request_model.dart';
import 'package:popytka_ua/data/repositories/auth_repository.dart';
import 'package:popytka_ua/data/services/osrm_routing_service.dart';

class HomeScreen extends ConsumerStatefulWidget {
  const HomeScreen({super.key});

  @override
  ConsumerState<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends ConsumerState<HomeScreen>
    with TickerProviderStateMixin {
  final _fromController = TextEditingController();
  final _toController = TextEditingController();
  DateTime _selectedDate = DateTime.now();
  TimeOfDay _selectedTime = TimeOfDay.now();
  int _seats = 1;

  List<SearchEntry> _searchEntries = [];
  bool _isHistoryLoaded = false;
  late final AnimatedMapController _mapController;
  late final AnimationController _pulseController;

  // New state for live routing on main map
  LatLng? _fromLatLng;
  LatLng? _toLatLng;
  List<LatLng> _activeRoutePoints = [];
  bool _isSearchingRoute = false;

  @override
  void initState() {
    super.initState();
    _mapController = AnimatedMapController(vsync: this);
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1500),
    )..repeat();
    _loadSearchHistory();
  }

  Future<void> _loadSearchHistory() async {
    final service = ref.read(searchHistoryServiceProvider);
    final entries = await service.getDisplayEntries();
    if (mounted) {
      setState(() {
        _searchEntries = entries;
        _isHistoryLoaded = true;
      });
    }
  }

  Future<void> _updateActiveRoute() async {
    if (_fromLatLng != null && _toLatLng != null) {
      setState(() => _isSearchingRoute = true);
      
      final points = await ref.read(osrmRoutingServiceProvider).getRoute(_fromLatLng!, _toLatLng!);
      
      if (mounted) {
        setState(() {
          _activeRoutePoints = points;
          _isSearchingRoute = false;
        });

        // Auto-fit to the route
        if (points.isNotEmpty) {
          final bounds = LatLngBounds.fromPoints(points);
          _mapController.animatedFitCamera(
            cameraFit: CameraFit.bounds(
              bounds: bounds,
              padding: const EdgeInsets.symmetric(horizontal: 50, vertical: 150),
            ),
          );
        }
      }
    } else {
      setState(() {
        _activeRoutePoints = [];
        _isSearchingRoute = false;
      });
    }
  }

  void _onSearch() async {
    final from = _fromController.text.trim();
    final to = _toController.text.trim();

    if (from.isNotEmpty && to.isNotEmpty) {
      // 1. Try to get coordinates for routing if we don't have them yet
      if (_fromLatLng == null || _toLatLng == null) {
        final geocoder = NominatimService();
        final fromResults = await geocoder.searchAddress(from);
        final toResults = await geocoder.searchAddress(to);
        
        if (mounted) {
          setState(() {
            if (fromResults.isNotEmpty) _fromLatLng = LatLng(fromResults.first.latitude, fromResults.first.longitude);
            if (toResults.isNotEmpty) _toLatLng = LatLng(toResults.first.latitude, toResults.first.longitude);
          });
          // Start road routing immediately
          _updateActiveRoute();
        }
      } else {
        // We already have coordinates, just ensure route is updated
        _updateActiveRoute();
      }

      // 2. Save to local search history
      final service = ref.read(searchHistoryServiceProvider);
      service.addSearchEntry(from, to).then((_) => _loadSearchHistory());

      // 2. Create a Ride Request in Firebase if user is logged in
      final currentUser = ref.read(authRepositoryProvider).currentUser;
      if (currentUser != null) {
        final departureDateTime = DateTime(
          _selectedDate.year,
          _selectedDate.month,
          _selectedDate.day,
          _selectedTime.hour,
          _selectedTime.minute,
        );

        final request = RideRequestModel(
          id: '', // Generated by Firestore
          userId: currentUser.uid,
          fromCity: from,
          toCity: to,
          departureTime: departureDateTime,
          seatsRequired: _seats,
          createdAt: DateTime.now(),
        );

        ref.read(rideRequestRepositoryProvider).createRequest(request);
      }

      final dateStr = _selectedDate.toIso8601String().split('T').first;
      final timeStr = "${_selectedTime.hour}:${_selectedTime.minute}";
      
      if (!mounted) return;
      context.push(
        '/search_results?from=$from&to=$to&date=$dateStr&time=$timeStr&seats=$_seats',
      );
    }
  }

  void _onChipTap(SearchEntry entry) {
    setState(() {
      _fromController.text = entry.from;
      _toController.text = entry.to;
    });
    _onSearch();
  }

  @override
  void dispose() {
    _fromController.dispose();
    _toController.dispose();
    _mapController.dispose();
    _pulseController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final t = AppLocalizations.of(context)!;
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final onSurface = theme.colorScheme.onSurface;

    return Scaffold(
      extendBodyBehindAppBar: true,
      resizeToAvoidBottomInset: false,
      body: Stack(
        children: [
          // 1. MAP LAYER
          FlutterMap(
            mapController: _mapController.mapController,
            options: const MapOptions(
              initialCenter: LatLng(49.0, 31.0),
              initialZoom: 6.0,
            ),
            children: [
              TileLayer(
                urlTemplate: isDark
                    ? 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png'
                    : 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
                subdomains: const ['a', 'b', 'c', 'd'],
              ),
              StreamBuilder<List<RideModel>>(
                stream: ref.watch(rideRepositoryProvider).streamRides(),
                builder: (context, snapshot) {
                  // Case 1: Search in progress (even if only one field is filled)
                  // We hide other rides to focus on user's current intent
                  final isUserTyping = _fromController.text.isNotEmpty || _toController.text.isNotEmpty;
                  
                  if (isUserTyping) {
                    if (_fromLatLng != null && _toLatLng != null && _activeRoutePoints.isNotEmpty) {
                      return Stack(
                        children: [
                          PolylineLayer(
                            polylines: [
                              Polyline(
                                points: _activeRoutePoints,
                                color: AppColors.primary,
                                strokeWidth: 5.0,
                              ),
                            ],
                          ),
                          MarkerLayer(
                            markers: [
                              _buildPulsingMarker(_fromLatLng!.latitude, _fromLatLng!.longitude, isOrigin: true),
                              _buildPulsingMarker(_toLatLng!.latitude, _toLatLng!.longitude, isOrigin: false),
                            ],
                          ),
                        ],
                      );
                    }
                    // Show only single markers if search is incomplete
                    return MarkerLayer(
                      markers: [
                        if (_fromLatLng != null) _buildPulsingMarker(_fromLatLng!.latitude, _fromLatLng!.longitude, isOrigin: true),
                        if (_toLatLng != null) _buildPulsingMarker(_toLatLng!.latitude, _toLatLng!.longitude, isOrigin: false),
                      ],
                    );
                  }

                  // Case 2: No active search, show all available rides using real road points
                  if (!snapshot.hasData) return const SizedBox.shrink();
                  final rides = snapshot.data!;

                  final polylines = <Polyline>[];
                  final markers = <Marker>[];

                  for (final ride in rides) {
                    // Use stored road geometry if available, fallback to straight line
                    final points = ride.routePoints.isNotEmpty 
                        ? ride.routePoints 
                        : [
                            LatLng(ride.fromLocation.latitude, ride.fromLocation.longitude),
                            LatLng(ride.toLocation.latitude, ride.toLocation.longitude),
                          ];

                    polylines.add(
                      Polyline(
                        points: points,
                        color: AppColors.secondary.withValues(alpha: 0.4),
                        strokeWidth: 3.0,
                      ),
                    );

                    markers.add(_buildPulsingMarker(ride.fromLocation.latitude, ride.fromLocation.longitude, isOrigin: true));
                    markers.add(_buildPulsingMarker(ride.toLocation.latitude, ride.toLocation.longitude, isOrigin: false));
                  }

                  return Stack(
                    clipBehavior: Clip.none,
                    children: [
                      PolylineLayer(polylines: polylines),
                      MarkerLayer(markers: markers),
                    ],
                  );
                },
              ),
            ],
          ),
          
          // ROUTE LOADING INDICATOR
          if (_isSearchingRoute)
            Positioned(
              top: 100,
              left: 0,
              right: 0,
              child: Center(
                child: GlassContainer(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                  borderRadius: 20,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: AppColors.primary,
                        ),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        "Будуємо маршрут...",
                        style: TextStyle(
                          color: onSurface,
                          fontSize: 12,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          // 2. GRADIENT OVERLAY
          Positioned(
            left: 0,
            right: 0,
            bottom: 0,
            height: 300,
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.bottomCenter,
                  end: Alignment.topCenter,
                  colors: [
                    theme.scaffoldBackgroundColor,
                    theme.scaffoldBackgroundColor.withValues(alpha: 0.0),
                  ],
                ),
              ),
            ),
          ),
          // 3. SEARCH CARD
          Positioned(
            left: 16,
            right: 16,
            top: 100,
            bottom: 100 + MediaQuery.of(context).viewInsets.bottom,
            child: Align(
              alignment: Alignment.bottomCenter,
              child: SingleChildScrollView(
                child: GlassContainer(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    mainAxisSize: MainAxisSize.min,
                  children: [
                    // FROM with autocomplete
                    AddressAutocompleteField(
                      hintText: t.from_label,
                      icon: Icons.my_location,
                      controller: _fromController,
                      onAddressSelected: (result) {
                        setState(() {
                          _fromLatLng = LatLng(result.latitude, result.longitude);
                        });
                        _updateActiveRoute();
                      },
                    ),
                    Divider(color: onSurface.withValues(alpha: 0.1)),

                    // TO with autocomplete
                    AddressAutocompleteField(
                      hintText: t.to_label,
                      icon: Icons.location_on,
                      controller: _toController,
                      onAddressSelected: (result) {
                        setState(() {
                          _toLatLng = LatLng(result.latitude, result.longitude);
                        });
                        _updateActiveRoute();
                      },
                    ),
                    Divider(color: onSurface.withValues(alpha: 0.1)),

                    // DATE & TIME
                    Row(
                      children: [
                        Expanded(
                          child: InkWell(
                            onTap: _selectDate,
                            borderRadius: BorderRadius.circular(8),
                            child: Padding(
                              padding: const EdgeInsets.symmetric(vertical: 8),
                              child: _buildDateRow(
                                _formatDate(_selectedDate),
                                Icons.calendar_today,
                                onSurface,
                              ),
                            ),
                          ),
                        ),
                        Container(
                          width: 1,
                          height: 24,
                          color: onSurface.withValues(alpha: 0.1),
                          margin: const EdgeInsets.symmetric(horizontal: 8),
                        ),
                        Expanded(
                          child: InkWell(
                            onTap: _selectTime,
                            borderRadius: BorderRadius.circular(8),
                            child: Padding(
                              padding: const EdgeInsets.symmetric(vertical: 8),
                              child: _buildDateRow(
                                _selectedTime.format(context),
                                Icons.access_time,
                                onSurface,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                    Divider(color: onSurface.withValues(alpha: 0.1)),

                    // SEATS
                    Padding(
                      padding: const EdgeInsets.symmetric(vertical: 8),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              const Icon(
                                Icons.person_outline,
                                color: AppColors.secondary,
                              ),
                              const SizedBox(width: 12),
                              Text(
                                t.seats_label,
                                style: TextStyle(
                                  color: onSurface.withValues(alpha: 0.7),
                                  fontSize: 16,
                                ),
                              ),
                            ],
                          ),
                          Row(
                            children: [
                              IconButton(
                                onPressed: () {
                                  if (_seats > 1) setState(() => _seats--);
                                },
                                icon: const Icon(
                                  Icons.remove_circle_outline,
                                  color: AppColors.primary,
                                ),
                              ),
                              Text(
                                "$_seats",
                                style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                  color: onSurface,
                                ),
                              ),
                              IconButton(
                                onPressed: () {
                                  if (_seats < 8) setState(() => _seats++);
                                },
                                icon: const Icon(
                                  Icons.add_circle_outline,
                                  color: AppColors.primary,
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),

                    const SizedBox(height: 16),

                    // BUTTON
                    ElevatedButton(
                      onPressed: _onSearch,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.black,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12),
                        ),
                      ),
                      child: Text(
                        t.search_btn,
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
          // 4. RECENT SEARCHES / POPULAR ROUTES
          if (_isHistoryLoaded && _searchEntries.isNotEmpty)
            Positioned(
              top: 60,
              left: 16,
              right: 16,
              child: SingleChildScrollView(
                scrollDirection: Axis.horizontal,
                child: Row(
                  children: _searchEntries.map((entry) {
                    return Padding(
                      padding: const EdgeInsets.only(right: 8),
                      child: _buildChip(entry, onSurface, isDark),
                    );
                  }).toList(),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Future<void> _selectDate() async {
    final now = DateTime.now();
    final todayStart = DateTime(now.year, now.month, now.day);
    
    // Ensure initial date is not before minimum date to avoid crash
    DateTime tempPickedDate = _selectedDate.isBefore(todayStart) 
        ? todayStart 
        : _selectedDate;
        
    final theme = Theme.of(context);

    await showModalBottomSheet(
      context: context,
      backgroundColor: theme.colorScheme.surface,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (BuildContext builder) {
        return SizedBox(
          height: 300,
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(builder).pop(),
                    child: Text(
                      AppLocalizations.of(context)!.cancel,
                      style: TextStyle(
                        color: theme.colorScheme.onSurface.withValues(alpha: 0.5),
                      ),
                    ),
                  ),
                  TextButton(
                    onPressed: () => Navigator.of(builder).pop(tempPickedDate),
                    child: const Text(
                      'OK',
                      style: TextStyle(
                        color: AppColors.primary,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
              Expanded(
                child: CupertinoTheme(
                  data: CupertinoThemeData(
                    textTheme: CupertinoTextThemeData(
                      dateTimePickerTextStyle: TextStyle(
                        color: theme.colorScheme.onSurface,
                        fontSize: 22,
                      ),
                    ),
                  ),
                  child: CupertinoDatePicker(
                    mode: CupertinoDatePickerMode.date,
                    initialDateTime: tempPickedDate,
                    minimumDate: todayStart,
                    maximumDate: todayStart.add(const Duration(days: 365)),
                    onDateTimeChanged: (DateTime newDate) {
                      tempPickedDate = newDate;
                    },
                  ),
                ),
              ),
            ],
          ),
        );
      },
    ).then((pickedDate) {
      if (!mounted) return;
      if (pickedDate != null) {
        final date = pickedDate as DateTime;
        setState(() {
          _selectedDate = date;
          // If selected today, ensure time is not in the past
          final now = DateTime.now();
          if (_isToday(date)) {
            final nowTime = TimeOfDay.fromDateTime(now);
            if (_isBefore(nowTime, _selectedTime) == false) {
              _selectedTime = nowTime;
            }
          }
        });
      }
    });
  }

  Future<void> _selectTime() async {
    final now = DateTime.now();
    DateTime initialTime;
    
    if (_isToday(_selectedDate)) {
      // If today, initial time should be at least now
      if (_isBefore(TimeOfDay.fromDateTime(now), _selectedTime)) {
        initialTime = DateTime(now.year, now.month, now.day, _selectedTime.hour, _selectedTime.minute);
      } else {
        initialTime = now;
      }
    } else {
      initialTime = DateTime(now.year, now.month, now.day, _selectedTime.hour, _selectedTime.minute);
    }

    DateTime tempPickedTime = initialTime;
    final theme = Theme.of(context);

    await showModalBottomSheet(
      context: context,
      backgroundColor: theme.colorScheme.surface,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (BuildContext builder) {
        return SizedBox(
          height: 300,
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  TextButton(
                    onPressed: () => Navigator.of(builder).pop(),
                    child: Text(
                      AppLocalizations.of(context)!.cancel,
                      style: TextStyle(
                        color: theme.colorScheme.onSurface.withValues(alpha: 0.5),
                      ),
                    ),
                  ),
                  TextButton(
                    onPressed: () => Navigator.of(builder).pop(tempPickedTime),
                    child: const Text(
                      'OK',
                      style: TextStyle(
                        color: AppColors.primary,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
              Expanded(
                child: CupertinoTheme(
                  data: CupertinoThemeData(
                    textTheme: CupertinoTextThemeData(
                      dateTimePickerTextStyle: TextStyle(
                        color: theme.colorScheme.onSurface,
                        fontSize: 22,
                      ),
                    ),
                  ),
                  child: CupertinoDatePicker(
                    mode: CupertinoDatePickerMode.time,
                    use24hFormat: true,
                    initialDateTime: initialTime,
                    minimumDate: _isToday(_selectedDate) ? now.subtract(const Duration(minutes: 1)) : null,
                    onDateTimeChanged: (DateTime newTime) {
                      tempPickedTime = newTime;
                    },
                  ),
                ),
              ),
            ],
          ),
        );
      },
    ).then((pickedTime) {
      if (!mounted) return;
      if (pickedTime != null) {
        final selectedDateTime = pickedTime as DateTime;
        final now = DateTime.now();
        
        if (_isToday(_selectedDate) && selectedDateTime.isBefore(now)) {
          setState(() {
            _selectedTime = TimeOfDay.fromDateTime(now);
          });
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text(AppLocalizations.of(context)!.error_past_time)),
          );
          return;
        }

        final newTimeOfDay = TimeOfDay(
          hour: selectedDateTime.hour,
          minute: selectedDateTime.minute,
        );
        if (newTimeOfDay != _selectedTime) {
          setState(() {
            _selectedTime = newTimeOfDay;
          });
        }
      }
    });
  }

  bool _isToday(DateTime date) {
    final now = DateTime.now();
    return date.year == now.year && date.month == now.month && date.day == now.day;
  }

  bool _isBefore(TimeOfDay t1, TimeOfDay t2) {
    if (t1.hour < t2.hour) return true;
    if (t1.hour > t2.hour) return false;
    return t1.minute < t2.minute;
  }

  String _formatDate(DateTime date) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final selected = DateTime(date.year, date.month, date.day);

    if (selected == today) {
      return AppLocalizations.of(context)!.today_label;
    }

    return "${date.day.toString().padLeft(2, '0')}.${date.month.toString().padLeft(2, '0')}.${date.year}";
  }

  Widget _buildDateRow(String label, IconData icon, Color textColor) {
    return Row(
      children: [
        Icon(icon, color: AppColors.secondary, size: 20),
        const SizedBox(width: 8),
        Expanded(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w500,
              color: textColor,
            ),
            overflow: TextOverflow.ellipsis,
          ),
        ),
      ],
    );
  }

  Widget _buildChip(SearchEntry entry, Color textColor, bool isDark) {
    return GestureDetector(
      onTap: () => _onChipTap(entry),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        decoration: BoxDecoration(
          color: isDark ? Colors.black54 : Colors.white.withValues(alpha: 0.9),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: AppColors.primary.withValues(alpha: 0.3)),
          boxShadow: isDark
              ? null
              : [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 4,
                    offset: const Offset(0, 2),
                  ),
                ],
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.history, color: AppColors.secondary, size: 16),
            const SizedBox(width: 6),
            Text(
              entry.displayText,
              style: TextStyle(color: textColor, fontSize: 13),
            ),
          ],
        ),
      ),
    );
  }

  Marker _buildPulsingMarker(double lat, double lng, {bool isOrigin = true}) {
    final color = isOrigin ? AppColors.primary : AppColors.secondary;
    return Marker(
      point: LatLng(lat, lng),
      width: 40,
      height: 40,
      child: Stack(
        alignment: Alignment.center,
        children: [
          // Outer pulsing ring
          AnimatedBuilder(
            animation: _pulseController,
            builder: (context, child) {
              final val = _pulseController.value;
              return Opacity(
                opacity: 1.0 - val,
                child: Transform.scale(
                  scale: 1.0 + (val * 1.5),
                  child: Container(
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: color.withValues(alpha: 0.5),
                    ),
                  ),
                ),
              );
            },
          ),
          // Inner dot
          Container(
            width: 16,
            height: 16,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: color,
              border: Border.all(color: Colors.white, width: 2),
              boxShadow: [
                BoxShadow(
                  color: color.withValues(alpha: 0.8),
                  blurRadius: 10,
                  spreadRadius: 2,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
